# Generated by Django 4.1.4 on 2023-11-22 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_profile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('site_number', models.IntegerField(default=1)),
                ('domain', models.CharField(blank=True, max_length=250, null=True)),
                ('ecommerce', models.BooleanField(default=False)),
                ('user_support', models.BooleanField(default=False)),
                ('template_editing', models.BooleanField(default=False)),
                ('ai_assistant', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_premium_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MainSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='iblog/logo/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='iblog/icon/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_site', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('api_key', models.CharField(blank=True, max_length=1000, null=True, verbose_name='API Key')),
                ('image', models.ImageField(blank=True, null=True, upload_to='developers/images/')),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('x_account', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_users', to='account.plan'),
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_templates', to='account.templatecategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='account.developer'),
        ),
        migrations.AddField(
            model_name='template',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_templates', to='account.plan'),
        ),
    ]
