# Generated by Django 4.1.4 on 2023-11-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_plan_templatecategory_remove_profile_is_premium_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
