# Generated by Django 4.1.4 on 2023-11-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_plan_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['level', 'id']},
        ),
    ]
