# Generated by Django 4.1.4 on 2023-11-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_plan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='account.template'),
        ),
    ]
