# Generated by Django 4.1.4 on 2023-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_site_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
