# Generated by Django 4.1.4 on 2023-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='domain',
            field=models.BooleanField(default=False),
        ),
    ]
