# Generated by Django 4.1.4 on 2023-11-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='x_account',
            field=models.URLField(blank=True, null=True),
        ),
    ]
