# Generated by Django 4.1.4 on 2023-11-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_site_template'),
        ('blog', '0007_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_blogs', to='account.site'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogcategory'),
        ),
    ]
