# Generated by Django 4.1.4 on 2023-11-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_site_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
