# Generated by Django 4.1.4 on 2023-11-26 04:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_allow_comments_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
